BUG: Avoid duplication in stack trace of `linspace(a, b, num=1.5)`
Before this commit, the stack trace was:
```
Traceback (most recent call last):
  File "C:\Users\wiese\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\core\function_base.py", line 114, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<ipython-input-13-802b8c6e85f6>", line 1, in <module>
    np.linspace(1, 2, 1.5)
  File "<__array_function__ internals>", line 5, in linspace
  File "C:\Users\wiese\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\core\function_base.py", line 116, in linspace
    raise TypeError(
TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.
```

Now it is
```
Traceback (most recent call last):
  File "C:\Users\wiese\Repos\numeric-python\numpy\build\testenv\Lib\site-packages\numpy\core\function_base.py", line 114, in linspace
    num = operator.index(num)
TypeError: 'float' object cannot be interpreted as an integer
```

This noisy traceback was introduced in f4dfe833e3e037bb69113f7250fad3699f918cfc.