BUG: Allow `int` to be called on nested object arrays
Rather than assuming that any object array is self-referencing, we can just use PyEnter_RecursiveCall in:

* `__int__`
* `__float__`
* `__long__`
* `__hex__`
* `__oct__`

This works towards (but does _not_ fix) #9972, by not directly touching the `nb_*` slots ourselves.

Substantial code deduplication here. Error message is different, but perhaps also better:

```python
>>> int(np.array([None]))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' # now
TypeError: cannot convert to an int; scalar object is not a number #before
```