MAINT: Improve error message for legal but unsupported PEP3118 types
Relates to #12369

Traceback is now:

```
In [1]: from array import array
   ...: import numpy as np
   ...:
   ...: buf = array('u', ['q', 'w', 'e', 'r', 't'])
   ...: view = memoryview(buf)
   ...:

In [2]: np.array(view)
NotImplementedError: Unsupported PEP 3118 data type 'u' (UCS-2 strings)

The above exception was the direct cause of the following exception:

ValueError: 'u' is not a valid PEP 3118 buffer format string
```